# Generated by Django 2.1a1 on 2018-06-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('science_groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
