# Generated by Django 2.1a1 on 2018-06-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('science_groups', '0002_auto_20180605_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
