# Generated by Django 2.1a1 on 2018-06-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('science_groups', '0005_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teachers',
        ),
    ]
