# Generated by Django 2.1a1 on 2018-06-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('science_groups', '0006_auto_20180605_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('group_purpose', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
        migrations.AddField(
            model_name='science_group',
            name='students',
            field=models.ManyToManyField(to='science_groups.Student'),
        ),
        migrations.AddField(
            model_name='science_group',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='science_groups.Teacher'),
        ),
    ]
