# Generated by Django 2.1a1 on 2018-06-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('science_groups', '0007_auto_20180605_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='science_group',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
