# Generated by Django 2.1a1 on 2018-06-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science_groups', '0013_auto_20180605_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(unique=True),
        ),
    ]
